# Generated by Django 5.2.7 on 2025-11-04 16:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Title of the auction item', max_length=200, null=True)),
                ('short_description', models.CharField(max_length=255)),
                ('description_document', models.FileField(blank=True, help_text='Optional PDF or Word doc with full presentation', null=True, upload_to='auction/descriptions/')),
                ('quantity', models.IntegerField(help_text='Quantity of items available in this auction')),
                ('starting_price', models.DecimalField(blank=True, decimal_places=2, help_text='Starting bid price for the auction', max_digits=10, null=True)),
                ('condition', models.CharField(choices=[('NEW', 'NEW'), ('ALMOST_NEW', 'ALMOST NEW'), ('USED_GOOD', 'USED IN GOOD CONDITION'), ('USED', 'USED')], default='NEW', max_length=20)),
                ('start_datetime', models.DateTimeField(help_text='ITEM AUCTION Starting DATE & TIME')),
                ('duration_minutes', models.PositiveIntegerField(help_text='DURATION in minutes (merchant-controlled)')),
                ('is_active', models.BooleanField(default=True, help_text='If False, auction is considered closed/terminated by provider.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='AuctionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='auction/images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('auction_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='auction.auctionitem')),
            ],
        ),
        migrations.CreateModel(
            name='AuctionVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, null=True, upload_to='auction/videos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('auction_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='auction.auctionitem')),
            ],
        ),
        migrations.AddField(
            model_name='auctionitem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='auction_items', to='auction.category'),
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted', models.BooleanField(default=False)),
                ('auction_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='auction.auctionitem')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='provider_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AuctionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_of_measure', models.CharField(max_length=50)),
                ('price_per_unit_of_measure', models.DecimalField(decimal_places=2, max_digits=10)),
                ('condition', models.CharField(max_length=20)),
                ('merchant_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sold_price_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_datetime', models.DateTimeField()),
                ('sold_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('shipped_delivered', models.BooleanField(default=False)),
                ('received_accepted', models.BooleanField(default=False)),
                ('auction_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='auction.auctionitem')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='auction.provider')),
            ],
        ),
        migrations.AddField(
            model_name='auctionitem',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction_items', to='auction.provider'),
        ),
    ]
