# Generated by Django 5.2.7 on 2025-11-07 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_remove_category_description_category_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionitem',
            name='duration_minutes',
        ),
        migrations.RemoveField(
            model_name='auctionresult',
            name='price_per_unit_of_measure',
        ),
        migrations.RemoveField(
            model_name='auctionresult',
            name='received_accepted',
        ),
        migrations.RemoveField(
            model_name='auctionresult',
            name='shipped_delivered',
        ),
        migrations.RemoveField(
            model_name='auctionresult',
            name='unit_of_measure',
        ),
        migrations.AddField(
            model_name='auctionitem',
            name='duration_days',
            field=models.PositiveIntegerField(blank=True, help_text='DURATION in days (merchant-controlled)', null=True),
        ),
        migrations.AlterField(
            model_name='auctionitem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction_items', to='auction.category'),
        ),
    ]
