# Generated by Django 5.2.7 on 2025-11-07 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0003_remove_auctionitem_duration_minutes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionitem',
            name='duration_days',
            field=models.PositiveIntegerField(blank=True, default=1, help_text='DURATION in days (merchant-controlled)', null=True),
        ),
    ]
