# Generated by Django 5.2.7 on 2025-11-10 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0004_alter_auctionitem_duration_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionitem',
            name='starting_price',
        ),
        migrations.AddField(
            model_name='auctionitem',
            name='price_per_unit_of_measure',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Merchant starting/list price per Unit of Measure', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='auctionitem',
            name='unit_of_measure',
            field=models.IntegerField(blank=True, help_text='Unit of Measure', null=True),
        ),
        migrations.AddField(
            model_name='auctionitem',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Buy unit price', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='auctionresult',
            name='price_per_unit_of_measure',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='auctionresult',
            name='unit_of_measure',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auctionitem',
            name='quantity',
            field=models.IntegerField(help_text='Offer by quantity'),
        ),
    ]
