# Generated by Django 5.2.7 on 2025-11-10 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0005_remove_auctionitem_starting_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionitem',
            name='price_per_unit_of_measure',
        ),
        migrations.RemoveField(
            model_name='auctionresult',
            name='price_per_unit_of_measure',
        ),
        migrations.AddField(
            model_name='auctionitem',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total price (calculated as quantity * unit price)', max_digits=10, null=True),
        ),
    ]
