# Generated by Django 5.2.7 on 2025-11-10 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0006_remove_auctionitem_price_per_unit_of_measure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionitem',
            name='unit_of_measure',
            field=models.CharField(blank=True, help_text='Unit of Measure', max_length=50, null=True),
        ),
    ]
