# Generated by Django 5.2.7 on 2025-11-10 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0007_alter_auctionitem_unit_of_measure'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionitem',
            name='asking_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional asking price (if different from total price)', max_digits=10, null=True),
        ),
    ]
