# Generated by Django 5.2.7 on 2025-11-11 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0008_auctionitem_asking_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionitem',
            name='quantity',
        ),
        migrations.AddField(
            model_name='auctionitem',
            name='quantity_available',
            field=models.PositiveIntegerField(blank=True, help_text='Quantity available for sale', null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='offer_quantity',
            field=models.PositiveIntegerField(default=1, help_text='Quantity customer wants to buy'),
        ),
        migrations.AddField(
            model_name='offer',
            name='offer_unit_price',
            field=models.DecimalField(decimal_places=2, help_text='Offer price per unit', max_digits=10, null=True),
        ),
    ]
