# Generated by Django 5.2.7 on 2025-11-11 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0009_remove_auctionitem_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionitem',
            name='asking_price',
        ),
        migrations.AlterField(
            model_name='auctionitem',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total price (calculated as quantity_available * unit price)', max_digits=10, null=True),
        ),
    ]
