# Generated by Django 5.2.7 on 2025-11-11 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0010_remove_auctionitem_asking_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionitem',
            name='is_cloased',
            field=models.BooleanField(default=False),
        ),
    ]
