# Generated by Django 5.2.7 on 2025-11-11 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0011_auctionitem_is_cloased'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionresult',
            name='offer_quantity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auction.offer'),
        ),
    ]
