# Generated by Django 5.2.7 on 2025-12-28 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0012_auctionresult_offer_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('ACCEPTED', 'Accepted'), ('WITHDRAWN', 'Withdrawn')], default='DRAFT', max_length=12),
        ),
        migrations.AddField(
            model_name='offer',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
