# Generated by Django 5.2.7 on 2025-11-29 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_image_course_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='available_days',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='course',
            name='daily_end_time',
            field=models.TimeField(blank=True, help_text='Latest time you can schedule classes each day', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='daily_start_time',
            field=models.TimeField(blank=True, help_text='Earliest time you can schedule classes each day', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
