# Generated by Django 5.2.7 on 2025-11-30 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_available_days_course_daily_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='available_days',
        ),
        migrations.RemoveField(
            model_name='course',
            name='daily_end_time',
        ),
        migrations.RemoveField(
            model_name='course',
            name='daily_start_time',
        ),
    ]
