# Generated by Django 5.2.7 on 2025-11-30 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_remove_course_available_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='available_days',
            field=models.CharField(blank=True, help_text='Comma separated weekdays (0=Monday, 6=Sunday)', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='daily_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='daily_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
