# Generated by Django 5.2.7 on 2025-12-01 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_available_days_course_daily_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='available_days',
            field=models.CharField(blank=True, help_text='Comma separated weekdays (0=Monday, 6=Sunday)', max_length=100),
        ),
    ]
